# Multi Container Pod : A pod with multiple containers

apiVersion: v1
kind: Pod
metadata:
  name: multi-c-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: mongo
    image: mongo 
