# Multi Container Pod : A pod with multiple containers

apiVersion: v1
kind: Pod
metadata:
  name: multi-c-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
    - name: GAME_NAME
      value: "PubG" 
    - name: ENVIRONMENT 
      value: "dev" 
    - name: MONGO_DNS 
      value: "mongo.robot.internal"
    - name: MONGO_PORT
      value: 27017 
    - name: OWNER
      value: "DevOps Alpha"