# Creates secrets ; Ensure you supply the sensitive information in base64 format

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  USER_NAME: cm9ib3QK
  PASSWORD: cm9ib1Nob3AtMQo= 

--- 

# Creates the pod  and injects the pod with the secret named mysecret
apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    envFrom:                                # envFrom : to inject a configMap
      - secretRef:
          name: mysecret