apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest 
--- 

# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-myservicea
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: myservicea.foo.org
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: myservicea
#           servicePort: 80